# Generated by Django 4.2.7 on 2023-11-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('slug', models.SlugField(max_length=20)),
                ('job', models.CharField(max_length=20)),
                ('avatar', models.ImageField(upload_to='')),
            ],
            options={
                'ordering': ['first_name'],
                'indexes': [models.Index(fields=['first_name'], name='judge_judge_first_n_2235b7_idx')],
            },
        ),
    ]
