# Generated by Django 4.2.7 on 2023-12-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("judge", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="judge",
            options={"ordering": ["id"]},
        ),
        migrations.AddField(
            model_name="judge",
            name="description",
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
