# Generated by Django 4.2.7 on 2023-12-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("judge", "0002_alter_judge_options_judge_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="judge",
            name="slug",
            field=models.SlugField(max_length=20, unique=True),
        ),
    ]
