# Generated by Django 4.2.7 on 2023-12-10 23:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("judge", "0003_alter_judge_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="judge",
            name="role",
            field=models.CharField(default="Concursante", max_length=20),
            preserve_default=False,
        ),
    ]
