# Generated by Django 4.2.7 on 2023-11-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("juried", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="juried",
            options={"ordering": ["first_name"]},
        ),
        migrations.RemoveIndex(
            model_name="juried",
            name="juried_juri_name_b7d8db_idx",
        ),
        migrations.RenameField(
            model_name="juried",
            old_name="name",
            new_name="first_name",
        ),
        migrations.AddField(
            model_name="juried",
            name="avatar",
            field=models.ImageField(default=1, upload_to=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="juried",
            name="job",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="juried",
            name="slug",
            field=models.SlugField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="juried",
            index=models.Index(
                fields=["first_name"], name="juried_juri_first_n_55664e_idx"
            ),
        ),
    ]
