# Generated by Django 4.2.7 on 2023-11-30 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contestant", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MusicStyle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("slug", models.SlugField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name="contestant",
            options={"ordering": ["first_name"]},
        ),
        migrations.RemoveIndex(
            model_name="contestant",
            name="contestant__name_aa6603_idx",
        ),
        migrations.RenameField(
            model_name="contestant",
            old_name="name",
            new_name="city",
        ),
        migrations.RenameField(
            model_name="contestant",
            old_name="province",
            new_name="first_name",
        ),
        migrations.AddField(
            model_name="contestant",
            name="avatar",
            field=models.ImageField(default="1", upload_to=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contestant",
            name="birthdate",
            field=models.DateField(default="2000-01-01"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contestant",
            name="hobbies",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contestant",
            name="job",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contestant",
            name="slug",
            field=models.SlugField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="contestant",
            index=models.Index(
                fields=["first_name"], name="contestant__first_n_c56a33_idx"
            ),
        ),
        migrations.AddField(
            model_name="contestant",
            name="music_style",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="contestant.musicstyle",
            ),
            preserve_default=False,
        ),
    ]
