# Generated by Django 4.2.7 on 2023-12-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestant', '0002_musicstyle_alter_contestant_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='hobbies',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='job',
            field=models.CharField(max_length=50),
        ),
    ]
