# Generated by Django 4.2.7 on 2023-12-05 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contestant', '0004_alter_contestant_city_alter_contestant_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contestant',
            options={'ordering': ['id']},
        ),
    ]
