# Generated by Django 4.2.7 on 2023-12-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contestant", "0006_alter_contestant_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contestant",
            name="slug",
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
