# Generated by Django 4.2.7 on 2023-11-22 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('function', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='teacher_tea_name_dc64d2_idx')],
            },
        ),
    ]
