# Generated by Django 4.2.7 on 2023-11-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teacher", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teacher",
            options={"ordering": ["first_name"]},
        ),
        migrations.RemoveIndex(
            model_name="teacher",
            name="teacher_tea_name_dc64d2_idx",
        ),
        migrations.RenameField(
            model_name="teacher",
            old_name="function",
            new_name="first_name",
        ),
        migrations.RenameField(
            model_name="teacher",
            old_name="name",
            new_name="subject",
        ),
        migrations.AddField(
            model_name="teacher",
            name="avatar",
            field=models.ImageField(default=1, upload_to=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="teacher",
            name="slug",
            field=models.SlugField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="teacher",
            index=models.Index(
                fields=["first_name"], name="teacher_tea_first_n_13383b_idx"
            ),
        ),
    ]
