# Generated by Django 4.2.7 on 2023-12-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teacher", "0004_alter_teacher_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="description",
            field=models.CharField(default=1, max_length=600),
            preserve_default=False,
        ),
    ]
